// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vauclgxijivkschqkwjh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZhdWNsZ3hpaml2a3NjaHFrd2poIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc5Nzk5NzAsImV4cCI6MjA1MzU1NTk3MH0.57AZkvoTuFhDoflJXo9AGIMw2m26D269kJNO9H_OgnQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);